# SPDX-License-Identifier: Apache-2.0
# Zephyr 4.x 用 board definition for seeeduino_xiao_ble

name: seeeduino_xiao_ble
vendor: lowprokb
socs:
  - name: nrf52840
revisions:
  - name: 1.0.0
    default: true
