include:
  - board: seeeduino_xiao_ble
    shield: zk_L
    cmake-args: "-DCONFIG_ZMK_KEYMAP_NAME=\"zk\""
  - board: seeeduino_xiao_ble
    shield: zonkey_R nice_oled
    cmake-args: "-DCONFIG_ZMK_KEYMAP_NAME=\"zk\""
