include:
  - board: seeeduino_xiao_ble
    shield: zonkey_R nice_oled
  - board: seeeduino_xiao_ble
    shield: zk_L
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: settings_reset
